problem:
  name: "surface_mine_large.problem" # [surface_mine_small.problem, surface_mine_moderate.problem, surface_mine_large.problem]
  plot: False

# Parameters for Traveling Salesman Problem
tsp:
  clustering: 'kmeans2'            # [STUDENTS TODO: implement better method than the default] Clustering method of viewpoints: [random (default), kmeans]
  distance_estimates: 'euclidean' # Method for evaluating cost of paths in TSP heuristic: [euclidean (default), astar, rrt, rrtstar]

# Parameters for path planning
path_planner:
  timeout: 100.0              # (s) timeout for single start-to-goal planning
  method: 'astar'              # [STUDENTS TODO: implement better method than the default] Method for generating start-to-goal paths: [euclidean, astar, rrt (default), rrtstar]
  straighten_paths: true    # [STUDENTS TODO: implement better method than the default] Path straightening flag (default: false)

  # RRT and RRT* method parameters
  rrt:
    branch_size: 3.0 # (m)
    sampling:
      method: 'gaussian' # [STUDENTS TODO: implement better method than the default] Method for sampling random points: [uniform (default), gaussian]
      gaussian:
        stddev_inflation: 1.5 # Inflation of standard deviation in all axes during gaussian sampling (m)
    star:
      neighborhood: 1 # (m)

  # A* method parameters
  astar:
    grid_resolution: 0.25 # (m)
    # Notes by Haizhou Zhang, Aug.1: 
    # if grid_resolution is too small, the A* algorithm will take a long time to compute the path, so longer solution time
    # if grid_resolution is too large, the path will be not smooth and precise enough, tend to collide
    # so far, 0.3 seems to be a good value, if 0.4, they collide a lot
    # but need more tuning after we modify the other algorithms


# Parameters for path smoothing
path_smoothing:
  sampling_step: 0.2  # (m) If horizontal constraints are not satisfied, TOPPRA might have returned infeasible trajectory due to too small sampling step
  lookahead_dist: 0.45 # (m) STUDENTS TODO: find optimal value than the default] Lookahead distance for path smoothing (default: 1.0 m) 

# Parameters for sampling the UAVs' trajectories [TIP: do path straightening before attempting parametrization]
trajectory_sampling:
  with_stops: false # [STUDENTS TODO: implement better method than the default] If true, UAVs will stop at each waypoint (default: true)

# Parameters for UAV-to-UAV collision avoidance
collision_avoidance:
  method: 'delay_till_no_collisions_occur' # [STUDENTS TODO: implement better method than the default] [none (default), delay_2nd_till_1st_UAV_finishes, delay_till_no_collisions_occur]

# Simulation-specific parameters
simulation:
  flight_always_allowed: true # If true, the simulation of flight will start even if the trajectory will not conform all constraints

# Visualization parameters
visualization:
  rviz:
    use:            True
    playback_speed: 3.0
    horizon_length: 20

  python:
    trajectories:      False
    dynamics:          False
    mutual_distance:   False
    obstacle_distance: False
