world_origin:

  units: "LATLON" # {"UTM, "LATLON"}

  origin_x: 47.397743
  origin_y: 8.545594

safety_area:

  enabled: true

  horizontal:

    # the frame of reference in which the points are expressed
    frame_name: "world_origin"

    # polygon
    #
    # x, y [m] for any frame_name except latlon_origin
    # x = latitude, y = longitude [deg]  for frame_name=="latlon_origin"
    points: [
      37.5, 25,
      37.5, -25,
      -37.5, -25,
      -37.5, 25
    ]

  vertical:

    # the frame of reference in which the max&min z is expressed
    frame_name: "world_origin"

    max_z: 9.0
    min_z: -4.0
